"""
make_tables.py — write the LaTeX result tables straight from results_v2/.

    python analyze.py && python make_tables.py

Every number that appears in the paper is generated here from the raw run
files, so the manuscript cannot drift away from the data. Output goes to
tables_v2/*.tex and each file is meant to be \\input{} by the manuscript.
"""
import glob
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
RES = ROOT / "results_v2"
OUT = ROOT / "tables_v2"
OUT.mkdir(exist_ok=True)

CLASSES = ["S", "M", "L", "XL"]
MAIN_ORDER = ["VNS", "ALNS+", "DRL-ALNS", "VNS-9", "Fixed-small", "Random-9",
              "Roulette-9", "Marginal-9", "DRL-VNS"]
F18_ORDER = ["VNS-18", "Fixed-dominant", "Random-18", "Roulette-18",
             "Marginal-18", "DRL-VNS18"]


def load(pattern):
    frames = []
    for f in glob.glob(str(RES / pattern)):
        try:
            d = pd.read_csv(f)
        except pd.errors.EmptyDataError:
            continue
        if len(d):
            frames.append(d)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_exact():
    """All exact runs, keeping for each instance the proven optimum if one
    exists and otherwise the longest attempt."""
    ex = pd.concat([load("exact_milp_shard*.csv"),
                    load("exact_milp_n12_shard*.csv"),
                    load("exact_milp_n12long_s*.csv")], ignore_index=True)
    if ex.empty:
        return ex
    ex["proven"] = ex["proven"].astype(bool)
    ex = ex.sort_values(["proven", "time_s"], ascending=[False, False])
    return ex.drop_duplicates(subset="instance", keep="first").reset_index(drop=True)


def esc(s):
    return str(s).replace("_", "\\_").replace("%", "\\%")


def write(name, lines):
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", name)


def table_main(per, methods, name, caption, label):
    """Improvement over Clarke-Wright per size class, mean of the runs."""
    rows = ["% generated by make_tables.py",
            "\\begin{table*}[t]", "\\centering", f"\\caption{{{caption}}}",
            f"\\label{{{label}}}", "\\small",
            "\\begin{tabular}{@{}l" + "r" * (len(methods) + 1) + "@{}}",
            "\\toprule",
            "Class & CW & " + " & ".join(esc(m) for m in methods) + " \\\\",
            "\\midrule"]
    for sc in CLASSES + ["Overall"]:
        sub = per if sc == "Overall" else per[per.size_class == sc]
        cw = sub[sub.method == methods[0]].Z_cw.mean()
        cells = []
        best = max(sub[sub.method == m].impr_pct.mean() for m in methods
                   if len(sub[sub.method == m]))
        for m in methods:
            s = sub[sub.method == m]
            if not len(s):
                cells.append("--")
                continue
            v = s.impr_pct.mean()
            txt = f"{s.mean_Z.mean():.1f} ({v:.2f}\\%)"
            cells.append(f"\\textbf{{{txt}}}" if abs(v - best) < 1e-9 else txt)
        label_sc = "Overall" if sc == "Overall" else f"Class {sc}"
        rows.append(f"{label_sc} & {cw:.1f} & " + " & ".join(cells) + " \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    write(name, rows)


def table_stats(st, scopes, name, caption, label, proposed="DRL-VNS"):
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering", f"\\caption{{{caption}}}",
            f"\\label{{{label}}}", "\\small",
            "\\begin{tabular}{@{}llrrrl@{}}", "\\toprule",
            "Scope & Comparison & W/L/T & Median diff. & $p$ (Holm) & \\\\",
            "\\midrule"]
    for sc in scopes:
        sub = st[(st.scope == sc) & (st.comparison.str.startswith(proposed))]
        for _, r in sub.iterrows():
            other = r.comparison.split(" vs ")[1]
            p = r.p_holm
            ptxt = "$<0.001$" if p < 0.001 else f"{p:.3f}"
            rows.append(f"{sc} & {esc(other)} & "
                        f"{int(r.wins)}/{int(r.losses)}/{int(r.ties)} & "
                        f"{r.median_diff_pct:+.3f}\\% & {ptxt} & {r.sig} \\\\")
        rows.append("\\midrule")
    rows[-1] = "\\bottomrule"
    rows += ["\\end{tabular}", "\\end{table}"]
    write(name, rows)


def table_exact():
    ex = load_exact()
    g = pd.read_csv(RES / "exact_gaps.csv") if (RES / "exact_gaps.csv").exists() else pd.DataFrame()
    if ex.empty:
        return
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{Exact solutions of the small instances. The solver is "
            "CBC 2.10.3 through PuLP with a zero gap tolerance; $K$ is the "
            "number of vehicle copies in the model and ``used'' the number the "
            "optimum employs. Re-solving every proven instance with $K+1$ "
            "copies returned the same optimal value.}",
            "\\label{tab:exactsolver}", "\\small",
            "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
            "$n$ & instances & proven & mean time (s) & mean $K$ & mean used \\\\",
            "\\midrule"]
    for n in sorted(ex.n.unique()):
        s = ex[ex.n == n]
        rows.append(f"{n} & {len(s)} & {int(s.proven.sum())} & "
                    f"{s.time_s.mean():.0f} & {s.K.mean():.1f} & "
                    f"{s.vehicles_used.mean():.1f} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tab_exactsolver.tex", rows)

    if g.empty:
        return
    pr = g[g.proven == True]
    methods = [m for m in MAIN_ORDER + F18_ORDER if m in set(pr.method)]
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{Gap to the proven optimum on the instances solved "
            "exactly, in per cent. ``mean'' averages the ten runs of each "
            "instance, ``best'' takes the best run, and ``at optimum'' is the "
            "share of instances whose mean run reaches the optimum.}",
            "\\label{tab:exactgaps}", "\\small",
            "\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
            "Method & mean gap & best gap & at optimum \\\\", "\\midrule"]
    for m in methods:
        s = pr[pr.method == m]
        opt = (s.mean_gap_pct < 0.005).mean() * 100
        rows.append(f"{esc(m)} & {s.mean_gap_pct.mean():.3f} & "
                    f"{s.best_gap_pct.mean():.3f} & {opt:.0f}\\% \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tab_exactgaps.tex", rows)


def table_poc():
    p = load("runs_poc_shard*.csv")
    if p.empty:
        return
    agg = p.groupby(["n", "config"]).agg(
        Z=("Z_best", "mean"), sd=("Z_best", "std"),
        splits=("split_customers", "mean"),
        extra=("extra_visits", "mean")).reset_index()
    base = agg[agg.config == "SDVRP"].set_index("n")
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{Price of control. Each configuration is solved with VNS "
            "under the same budget (five runs per instance, five instances per "
            "size). Cost is relative to the unconstrained SDVRP and ``splits'' "
            "is the mean number of customers served by more than one vehicle.}",
            "\\label{tab:poc}", "\\small",
            "\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
            "Configuration & $n=15$ & $n=30$ & $n=50$ & $n=75$ \\\\",
            "\\midrule", "\\multicolumn{5}{@{}l}{\\emph{cost relative to SDVRP}}\\\\"]
    sizes = sorted(agg.n.unique())
    for cfg in ["FULL", "no-N1", "no-N2", "no-N3"]:
        s = agg[agg.config == cfg].set_index("n")
        cells = [f"{(s.Z[n]-base.Z[n])/base.Z[n]*100:+.2f}\\%" for n in sizes]
        rows.append(f"{esc(cfg)} & " + " & ".join(cells) + " \\\\")
    rows.append("\\midrule")
    rows.append("\\multicolumn{5}{@{}l}{\\emph{split customers}}\\\\")
    for cfg in ["FULL", "no-N1", "no-N2", "no-N3", "SDVRP"]:
        s = agg[agg.config == cfg].set_index("n")
        cells = [f"{s.splits[n]:.1f}" for n in sizes]
        rows.append(f"{esc(cfg)} & " + " & ".join(cells) + " \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tab_poc.tex", rows)


def table_case():
    f = RES / "case_study.csv"
    if not f.exists():
        return
    c = pd.read_csv(f).sort_values("mean_Z")
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{NUPCO--Riyadh case study ($n=30$), ten runs per method "
            "under a 30\\,s CPU budget. The Clarke--Wright reference is "
            f"{c.cw.iloc[0]:.1f}.}}",
            "\\label{tab:case}", "\\small",
            "\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
            "Method & mean & s.d. & best & improvement \\\\", "\\midrule"]
    for _, r in c.iterrows():
        rows.append(f"{esc(r.method)} & {r.mean_Z:.1f} & {r.sd_Z:.1f} & "
                    f"{r.best_Z:.1f} & {r.impr_pct:.2f}\\% \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tab_case.tex", rows)


def table_sdvrp():
    s = load("sdvrp_set1_shard*.csv")
    if s.empty:
        return
    per = s.groupby(["instance", "n", "method"]).agg(
        mean_Z=("Z_best", "mean"), best_Z=("Z_best", "min"),
        bks=("best_known", "first")).reset_index()
    per["mean_gap"] = (per.mean_Z - per.bks) / per.bks * 100
    per["best_gap"] = (per.best_Z - per.bks) / per.bks * 100
    methods = [m for m in ["VNS", "ALNS+", "VNS-9", "DRL-VNS"] if m in set(per.method)]
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{The same solvers on the classical SDVRP benchmark SET-1 "
            "(21 instances, $n$ from 8 to 288) with the three controls switched "
            "off. Gaps are against the best value reported by the seven solvers "
            "of the 12th DIMACS Implementation Challenge; three runs per "
            "instance under a 1--5 minute CPU budget.}",
            "\\label{tab:sdvrp}", "\\small",
            "\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
            "Method & mean gap & best gap & instances \\\\", "\\midrule"]
    for m in methods:
        sub = per[per.method == m]
        rows.append(f"{esc(m)} & {sub.mean_gap.mean():.2f}\\% & "
                    f"{sub.best_gap.mean():.2f}\\% & {len(sub)} \\\\")
    rows += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tab_sdvrp.tex", rows)


def table_sens():
    d = load("runs_sens_csens_shard*.csv")
    if d.empty:
        return
    d = d[d.suite == "sens"].copy()
    if d.empty:
        return
    d["param"] = d.config.str.split("=").str[0]
    d["value"] = d.config.str.split("=").str[1]
    rows = ["% generated by make_tables.py",
            "\\begin{table}[t]", "\\centering",
            "\\caption{Sensitivity of the model parameters, VNS under the "
            "standard budget (five runs on six instances per setting). The "
            "objective and the number of split customers are means.}",
            "\\label{tab:sens}", "\\small",
            "\\begin{tabular}{@{}llrrr@{}}", "\\toprule",
            "Parameter & value & objective & splits & extra visits \\\\",
            "\\midrule"]
    names = {"beta": "$\\beta_Q$", "mu": "$\\mu$", "delta": "$\\delta$",
             "umax": "$U_{\\max}$"}
    for p in ["beta", "mu", "delta", "umax"]:
        sub = d[(d.param == p) & (d.method == "VNS")]
        if sub.empty:
            continue
        for v in sorted(sub.value.unique(), key=float):
            s = sub[sub.value == v]
            rows.append(f"{names[p]} & {v} & {s.Z_best.mean():.1f} & "
                        f"{s.split_customers.mean():.2f} & "
                        f"{s.extra_visits.mean():.2f} \\\\")
        rows.append("\\midrule")
    rows[-1] = "\\bottomrule"
    rows += ["\\end{tabular}", "\\end{table}"]
    write("tab_sens.tex", rows)


def facts():
    """Key numbers as LaTeX macros, so the prose cannot drift from the data."""
    runs = pd.concat([load("runs_*_shard*.csv"), load("sdvrp_set1_shard*.csv")],
                     ignore_index=True)
    viol_cols = [c for c in ["demand_viol", "cap_viol", "n1_viol", "n2_viol",
                             "dup_visit_viol", "zero_qty_stops"] if c in runs]
    ex = load_exact()
    m = [f"% generated by make_tables.py",
         f"\\newcommand{{\\NRUNS}}{{{len(runs):,}}}",
         f"\\newcommand{{\\NVIOL}}{{{int(runs[viol_cols].sum().sum())}}}",
         f"\\newcommand{{\\MAXUTIL}}{{{runs.max_util.max():.4f}}}"]
    if not ex.empty:
        m += [f"\\newcommand{{\\NEXACT}}{{{len(ex)}}}",
              f"\\newcommand{{\\NPROVEN}}{{{int(ex.proven.sum())}}}"]
        pr = ex[ex.proven == True]
        if "K1_Z" in pr and pr.K1_Z.notna().any():
            same = int((abs(pr.K1_Z - pr.Z) < 1e-4).sum())
            m.append(f"\\newcommand{{\\NKONECHECK}}{{{same}}}")
    ips = runs[runs.suite == "main"].assign(x=lambda d: d.iters / d.cpu_s) \
        if "suite" in runs else pd.DataFrame()
    if len(ips):
        for meth, macro in [("DRL-VNS", "IPSDRLVNS"), ("VNS-9", "IPSVNSNINE"),
                            ("VNS", "IPSVNS")]:
            s = ips[ips.method == meth]
            if len(s):
                m.append(f"\\newcommand{{\\{macro}}}{{{s.x.mean():.0f}}}")
    write("facts.tex", m)


def main():
    per = pd.read_csv(RES / "per_instance.csv")
    st = pd.read_csv(RES / "statistics.csv")
    facts()
    methods9 = [m for m in MAIN_ORDER if m in set(per.method)]
    table_main(per[per.method.isin(methods9)], methods9, "tab_main.tex",
               "Mean objective and improvement over Clarke--Wright, ten runs "
               "per instance under an equal CPU budget. The best value in each "
               "row is in bold.", "tab:main")
    table_stats(st, ["Overall"] + CLASSES, "tab_stats.tex",
                "Two-sided Wilcoxon signed-rank tests of the proposed method "
                "against every other method on paired per-instance means, with "
                "Holm correction within each scope. W/L/T counts instances.",
                "tab:stats")
    m18 = [m for m in F18_ORDER if m in set(per.method)]
    if m18:
        table_main(per[per.method.isin(m18)], m18, "tab_main18.tex",
                   "The eighteen-action family, whose action set contains the "
                   "moves of the standard VNS baseline. Ten runs per instance "
                   "under the same budget.", "tab:main18")
    table_exact()
    table_poc()
    table_case()
    table_sdvrp()
    table_sens()


if __name__ == "__main__":
    main()
